ProductManagementAssignment/ProductManagement/ProductManagement/ProductManagement.WebUI/Controllers/ProductManagerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NLog;
using PagedList;
using ProductManagement.Core.Contracts;
using ProductManagement.Core.Models;
using ProductManagement.Core.ViewModels;
using ProductManagement.DataAccess.InMemory;

namespace ProductManagement.WebUI.Controllers
{
    public class ProductManagerController : Controller
    {
        private static Logger logger = LogManager.GetLogger("myAppLoggerRule");
        // GET: ProductManager
        IRepository<Product> context;
        IRepository<ProductCategory> productCategories;

        public ProductManagerController(IRepository<Product> productContext, IRepository<ProductCategory> productCategoryContext)
        {
            context = productContext;
            productCategories = productCategoryContext;
        }
        public ActionResult Index( string option=null,string search=null, int? pageNumber=null, string sort=null)
        {
            logger.Info("Entering the Product Manager Controller. Index Method");
            try
            {
                if (Session["Email"] != null)
                {



                    List<Product> products = context.Collection().ToList();


                    //if the sort parameter is null or empty then we are initializing the value as descending name  
                    ViewBag.SortByName = string.IsNullOrEmpty(sort) ? "descending name" : "";
                    //if the sort value is gender then we are initializing the value as descending gender  
                    ViewBag.SortByCategory = sort == "Category" ? "descending gender" : "Category";

                    //here we are converting the db.Students to AsQueryable so that we can invoke all the extension methods on variable records.  
                    var records = products.AsQueryable();
                    if (search != null)
                    {
                        if (option == "Category")
                        {

                            records = records.Where(x => x.Category.StartsWith(search) || search == null);

                        }
                        else
                        {
                            records = records.Where(x => x.Name.StartsWith(search) || search == null);
                        }
                    }


                    switch (sort)
                    {

                        case "descending name":
                            records = records.OrderByDescending(x => x.Name);
                            break;

                        case "descending category":
                            records = records.OrderByDescending(x => x.Category);
                            break;

                        case "Category":
                            records = records.OrderBy(x => x.Category);
                            break;

                        default:
                            records = records.OrderBy(x => x.Name);
                            break;

                    }
                    return View(records.ToPagedList(pageNumber ?? 1, 2));
                }
                else
                {
                    return RedirectToAction("Login", "Account");
                }
            }
            catch(Exception e)
            {
                logger.Error("Exception Occured - " + e.Message);
                return Content("Exception Occured" + e.Message);
            }
            

            
        }




        public ActionResult DeleteSelected(FormCollection formcollection)
        {
            
            
            
            if (formcollection["ids"] == null)
            {
                //throw error
                ModelState.AddModelError("", "No item selected to delete");
                return RedirectToAction("Index");
            }
            string[] idss = formcollection["ids"].Split(new char[] { ',' });

            foreach (string id in idss)
            {
                Product todo = context.Find(id);
                 //remove the record from the database
                context.Delete(todo);

            }
            //redirect to index view once record is deleted
            TempData["DeleteMessage"] = "Deleted Successfully";
            logger.Info("Multiple Records Deleted Successfully");
            return RedirectToAction("Index");

        }

        public ActionResult Create()
        {
            if (Session["Email"] != null) { 
            ProductManagerViewModel viewModel = new ProductManagerViewModel();

            viewModel.Product = new Product();
            viewModel.ProductCategories = productCategories.Collection(); ;
            return View(viewModel);
               }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        [HttpPost]
        public ActionResult Create(Product product,HttpPostedFileBase file)
        {
            try 
            {
                if (!ModelState.IsValid)
                {
                    return View(product);
                }
                else
                {
                    if (file != null)
                    {
                        product.Image = product.Id + Path.GetExtension(file.FileName);
                        file.SaveAs(Server.MapPath("//Content//ProductImages//") + product.Image);

                    }
                    context.Insert(product);
                    context.Commit();
                    TempData["CreateMessage"] = "Added Successfully";
                    logger.Info("New Product successfully added.");
                    return RedirectToAction("Index");
                }

            }
            catch (Exception e)
            {

                logger.Error("Exception Occured - " + e.Message);
                return Content("Exception Occured" + e.Message);
            }
            
        }


        public ActionResult Edit(string Id)
        {
            if (Session["Email"] != null)
            {

                Product product = context.Find(Id);
                if (product == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    ProductManagerViewModel viewModel = new ProductManagerViewModel();

                    viewModel.Product = product;
                    viewModel.ProductCategories = productCategories.Collection(); ;
                    return View(viewModel);
                }
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        [HttpPost]
        public ActionResult Edit(Product product, string Id,HttpPostedFileBase file)
        {
            try
            {
                Product productToEdit = context.Find(Id);
                if (productToEdit == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    if (!ModelState.IsValid)
                    {
                        return View(product);
                    }
                    if (file != null)
                    {
                        productToEdit.Image = product.Id + Path.GetExtension(file.FileName);
                        file.SaveAs(Server.MapPath("//Content//ProductImages//") + productToEdit.Image);

                    }
                    productToEdit.Category = product.Category;
                    productToEdit.Name = product.Name;
                    productToEdit.Description = product.Description;
                    productToEdit.Price = product.Price;
                    productToEdit.Quantity = product.Quantity;

                    context.Commit();
                    TempData["EditMessage"] = "Edited Successfully";
                    logger.Info("Product Edited successfully.");
                    return RedirectToAction("Index");

                }
            }
            catch(Exception e)
            {
                logger.Error("Exception Occured - " + e.Message);
                return Content("Exception Occured" + e.Message);
            }
            

        }

        public ActionResult Delete(string Id)
        {
            if (Session["Email"] != null)
            {



                Product productToDelete = context.Find(Id);
                if (productToDelete == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    return View(productToDelete);
                }
            }
            else
            {
                return RedirectToAction("Login","Account");
            }

        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult ConfirmDelete(string Id)
        {
            try
            {
                Product productToDelete = context.Find(Id);
                if (productToDelete == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    context.Delete(productToDelete);
                    TempData["DeleteMessage"] = "Deleted Successfully";
                    logger.Info("Product successfully Deleted.");
                    return RedirectToAction("Index");
                }
            }
            catch(Exception e)
            {
                logger.Error("Exception Occured - " + e.Message);
                return Content("Exception Occured" + e.Message);
            }


        }
    }
}

ProductManagementAssignment/ProductManagement/ProductManagement/ProductManagement.WebUI/Views/ProductManager/Create.cshtml
@model ProductManagement.Core.ViewModels.ProductManagerViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<script src="~/Scripts/jquery-3.5.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>



@using (Html.BeginForm("Create", "ProductManager", FormMethod.Post, new { encType = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Product.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Product.Category, new SelectList(Model.ProductCategories, "Category", "Category"), new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="file" name="file" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProductManagementAssignment/ProductManagement/ProductManagement/ProductManagement.WebUI/Views/ProductManager/Delete.cshtml
@model ProductManagement.Core.Models.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProductManagementAssignment/ProductManagement/ProductManagement/ProductManagement.WebUI/Views/ProductManager/Edit.cshtml
@model ProductManagement.Core.ViewModels.ProductManagerViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
<script src="~/Scripts/jquery-3.5.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>



@using (Html.BeginForm("Edit", "ProductManager", FormMethod.Post, new { encType = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Product.Id)

        <div class="col-md-2">
            <img class="img-responsive" src="~/Content/ProductImages/@Model.Product.Image" />
        </div>
        <div class="col-md-10">

            <div class="form-group">
                @Html.LabelFor(model => model.Product.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Product.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Product.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Product.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Product.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Product.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Product.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Product.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Product.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Product.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Product.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Product.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Product.Category, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Product.Category, new SelectList(Model.ProductCategories, "Category", "Category"), new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Product.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" id="file" name="file" class="form-control" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProductManagementAssignment/ProductManagement/ProductManagement/ProductManagement.WebUI/Views/ProductManager/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<ProductManagement.Core.Models.Product>

@{
    ViewBag.Title = "Index";
}



<h2>Index</h2>
@using (Html.BeginForm("Index", "ProductManager", FormMethod.Get))
{



    <b>Search Option: </b>@Html.RadioButton("option", "Name") <text>Name</text> @Html.RadioButton("option", "Category") <text> Category </text>



        @Html.TextBox("search", null, new { maxlength = 100, size = 20 })
        <input class="btn btn-primary" type="submit" name="submit" value="Search" />
    }
<br />

@using (Html.BeginForm("DeleteSelected", "ProductManager", FormMethod.Post))

{
    <p>


        <input type="submit" value="Delete Selected Products" onclick="return confirm('Are you sure you wish to delete selected Products?');" class="btn btn-danger" />

    </p>


    <p>
        @Html.ActionLink("Create New", "Create")
    </p>



    <br />

    <table class="table">
        <tr>
            <th>

            </th>
            <th>

            </th>
            <th>
                @Html.ActionLink("Name", "Index", new
           {
               sort = ViewBag.SortByName,

               search = Request.QueryString["search"]
           })
            <th>
                @Html.DisplayNameFor(model => model.First().Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Price)
            </th>
            <th>
                @Html.ActionLink("Category", "Index", new { sort = ViewBag.SortByCategory })

            </th>
            

            <th></th>
        </tr>

        @if (Model.Count() == 0)
        {
            <tr><td colspan="7" style="text-align:center;">Records not Found</td></tr>
        }
        else
        {

            foreach (var item in Model)
            {
                <tr>
                    <td>

                        <input type="checkbox" class="checkedBoxId " name="ids" value="@item.Id" />
                    </td>
                    <td>
                        <img class="img-thumbnail" style="height:70px;" src="~/Content/ProductImages/@item.Image" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category)
                    </td>
                    

                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }
        }

    </table>
}
@Html.PagedListPager(Model, pageNumber => Url.Action("Index", new
{
    pageNumber,
    search = Request.QueryString["search"],
    sort = Request.QueryString["sort"]
}))

@section scripts{
    <script>
        $(function () {
            var deleteMessage = '@TempData["DeleteMessage"]'
            if (deleteMessage != '') {
                alertify.success(deleteMessage);
            }

            var createMessage = '@TempData["CreateMessage"]'
            if (createMessage != '') {
                alertify.success(createMessage);
            }
            var editMessage = '@TempData["EditMessage"]'
            if (editMessage != '') {
                alertify.success(editMessage);
            }


        });
    </script>

}